app/config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  get 'users/create'
  # Defina a rota root 
  root 'livros#index'

   # Rotas de autenticação
   get 'login', to: 'sessions#new'
   post 'login', to: 'sessions#create'
   delete 'logout', to: 'sessions#destroy'
 
   # Rotas para usuários
   get 'signup', to: 'users#new'
   post 'signup', to: 'users#create'
   
  # Recursos para os controladores
  resources :funcionarios
  resources :usuarios
  resources :livros
  resources :emprestimos

  # Rota para verificar a saúde do Rails
  get "up" => "rails/health#show", as: :rails_health_check
end

app/app/models/funcionario.rb
class Funcionario < ApplicationRecord
end

app/app/controllers/funcionarios_controller.rb
class FuncionariosController < ApplicationController
  before_action :set_funcionario, only: %i[ show edit update destroy ]

 
  def index
    @funcionarios = Funcionario.all
  end

  def show
  end

  def new
    @funcionario = Funcionario.new
  end

  def edit
  end

  def create
    @funcionario = Funcionario.new(funcionario_params)

    respond_to do |format|
      if @funcionario.save
        format.html { redirect_to funcionario_url(@funcionario), notice: "Funcionario was successfully created." }
        format.json { render :show, status: :created, location: @funcionario }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end
  def update
    respond_to do |format|
      if @funcionario.update(funcionario_params)
        format.html { redirect_to funcionario_url(@funcionario), notice: "Funcionario was successfully updated." }
        format.json { render :show, status: :ok, location: @funcionario }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @funcionario.destroy!

    respond_to do |format|
      format.html { redirect_to funcionarios_url, notice: "Funcionario was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_funcionario
      @funcionario = Funcionario.find(params[:id])
    end

    def funcionario_params
      params.require(:funcionario).permit(:email, :senha)
    end
end

app/app/helpers/funcionarios_helper.rb
module FuncionariosHelper
end

app/app/views/funcionarios/_form.html.erb
<%= form_with(model: funcionario) do |form| %>
  <% if funcionario.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(funcionario.errors.count, "error") %> prohibited this funcionario from being saved:</h2>

      <ul>
        <% funcionario.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :senha, style: "display: block" %>
    <%= form.text_field :senha %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/app/views/funcionarios/_funcionario.html.erb
<div id="<%= dom_id funcionario %>">
  <p>
    <strong>Email:</strong>
    <%= funcionario.email %>
  </p>

  <p>
    <strong>Senha:</strong>
    <%= funcionario.senha %>
  </p>

</div>

app/app/views/funcionarios/edit.html.erb
<h1>Editing funcionario</h1>

<%= render "form", funcionario: @funcionario %>

<br>

<div>
  <%= link_to "Show this funcionario", @funcionario %> |
  <%= link_to "Back to funcionarios", funcionarios_path %>
</div>

app/app/views/funcionarios/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Funcionarios</h1>

<div id="funcionarios">
  <% @funcionarios.each do |funcionario| %>
    <%= render funcionario %>
    <p>
      <%= link_to "Show this funcionario", funcionario %>
    </p>
  <% end %>
</div>

<%= link_to "New funcionario", new_funcionario_path %>

app/app/views/funcionarios/new.html.erb
<h1>New funcionario</h1>

<%= render "form", funcionario: @funcionario %>

<br>

<div>
  <%= link_to "Back to funcionarios", funcionarios_path %>
</div>

app/app/views/funcionarios/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @funcionario %>

<div>
  <%= link_to "Edit this funcionario", edit_funcionario_path(@funcionario) %> |
  <%= link_to "Back to funcionarios", funcionarios_path %>

  <%= button_to "Destroy this funcionario", @funcionario, method: :delete %>
</div>