app/config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  get 'users/create'
  # Defina a rota root 
  root 'livros#index'

   # Rotas de autenticação
   get 'login', to: 'sessions#new'
   post 'login', to: 'sessions#create'
   delete 'logout', to: 'sessions#destroy'
 
   # Rotas para usuários
   get 'signup', to: 'users#new'
   post 'signup', to: 'users#create'
   
  # Recursos para os controladores
  resources :funcionarios
  resources :usuarios
  resources :livros
  resources :emprestimos

  # Rota para verificar a saúde do Rails
  get "up" => "rails/health#show", as: :rails_health_check
end

app/app/models/livro.rb
class Livro < ApplicationRecord
    
    validates :isbn, presence: { message: 'não pode ficar em branco' },
                     length: { is: 13, message: 'deve ter exatamente 13 caracteres' },
                     uniqueness: { message: 'já está em uso' }
  
    # Validações para os campos nome, autor e genero
    validates :nome, presence: { message: 'não pode ficar em branco' }
    validates :autor, presence: { message: 'não pode ficar em branco' }
    validates :genero, presence: { message: 'não pode ficar em branco' }
    after_initialize :set_default_disponivel, if: :new_record?
  
    private
  
    def set_default_disponivel
      self.disponivel ||= true
    end
  end
  

app/app/controllers/livros_controller.rb
class LivrosController < ApplicationController
  before_action :set_livro, only: %i[ show edit update destroy ]
  
def show
  @livro = Livro.find(params[:id])
  @show_detail = true
end

def index
  @livros = Livro.all
  @show_detail = false #adiciona detalhe mostrar livro 
end 

  def new
    @livro = Livro.new
  end

  def edit
  end

  def create
    @livro = Livro.new(livro_params)

    respond_to do |format|
      if @livro.save
        format.html { redirect_to livro_url(@livro) }
        format.json { render :show, status: :created, location: @livro }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @livro.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @livro.update(livro_params)
        format.html { redirect_to livro_url(@livro)}
        format.json { render :show, status: :ok, location: @livro }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @livro.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @livro.destroy!

    respond_to do |format|
      format.html { redirect_to livros_url }
      format.json { head :no_content }
    end
  end

  private
    def set_livro
      @livro = Livro.find(params[:id])
    end

    def livro_params
      params.require(:livro).permit(:nome, :isbn, :autor, :genero, :disponivel)
    end
end

app/app/helpers/livros_helper.rb
module LivrosHelper
end

app/app/views/livros/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-4 col-lg-3 font-roboto-mono">
      <%= form_with(model: livro, local: true) do |form| %>
        <% if livro.errors.any? %>
          <div class="alert alert-info">
            <h4 class="alert-heading fs-6"><%= pluralize(livro.errors.count, "Erro") %> Este livro não pode ser salvo</h4>
            <ul class="mb-0" style="font-size: 0.75rem; color: #007bff;"> 
              <% livro.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="mb-2">
          <%= form.label :nome, class: 'form-label fs-6' %>
          <%= form.text_field :nome, class: 'form-control form-control-sm bg-custom-color' %>
        </div>

        <div class="mb-2">
          <%= form.label :isbn, class: 'form-label fs-6' %>
          <%= form.text_field :isbn, class: 'form-control form-control-sm bg-custom-color' %>
        </div>

        <div class="mb-2">
          <%= form.label :autor, class: 'form-label fs-6' %>
          <%= form.text_field :autor, class: 'form-control form-control-sm bg-custom-color' %>
        </div>

        <div class="mb-2">
          <%= form.label :genero, class: 'form-label fs-6' %>
          <%= form.text_field :genero, class: 'form-control form-control-sm bg-custom-color' %>
        </div>

        <div class="d-flex justify-content-end mt-3 custom-btn padding-btn">
          <%= form.submit 'Salvar Livro', class: 'btn btn-primary custom-btn' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/app/views/livros/_livro.html.erb
<table class="table table-bordered font-roboto-mono w-75 mx-auto">
  <thead>
    <tr>
      <th>ID</th>
      <th>Nome</th>
      <th>Isbn</th>
      <th>Autor</th>
      <th>Gênero</th>
      <th>Disponibilidade</th>
      <% if !@show_detail %>
        <th>Ações</th> 
      <% end %>
    </tr>
  </thead>
  <tbody>
    <tr id="<%= dom_id livro %>">
      <td><%= livro.id %></td>
      <td><%= livro.nome %></td>
      <td><%= livro.isbn %></td>
      <td><%= livro.autor %></td>
      <td><%= livro.genero %></td>
      <td><%= livro.disponivel ? 'Disponível' : 'Indisponível' %></td>
      <% if !@show_detail %>
        <td>
          <%= link_to 'Mostrar Livro', livro_path(livro), class: 'link' %> 
        </td>
      <% end %>
    </tr>
  </tbody>
</table>

app/app/views/livros/edit.html.erb
<div class="position-absolute top-0 start-0 mt-3 ms-3 font-roboto-mono">
  <%= link_to livros_path, class: 'd-flex align-items-center link' do %>
    <i class="bi bi-arrow-return-left fs-3"></i>
    <span class="ms-2 fs-6">Voltar livro</span> 
  <% end %>
</div>

<div class="container d-flex justify-content-center align-items-center min-vh-100">
  <div class="content w-100" style="max-width: 1600px;">
    <%= render "form", livro: @livro %>
  </div>
</div>

app/app/views/livros/index.html.erb
<p style="color: green; font-family: 'Roboto Mono', sans-serif;"><%= notice %></p>

<div class="position-absolute top-0 start-0 mt-3 ms-3 font-roboto-mono">
  <div class="button-group">
    <%= link_to new_livro_path, class: 'd-flex align-items-center link' do %>
      <i class="bi bi-plus-square fs-4"></i>
      <span class="ms-2 fs-6">Criar Livro</span>
    <% end %>
    <%= link_to emprestimos_path, class: 'd-flex align-items-center link' do %>
      
      <i class="bi bi-bookmark fs-3"></i>
      <span class="ms-2 fs-6">Empréstimos</span>
    <% end %>
  </div>
</div>

<div id="livros" style="font-family: 'Roboto Mono', sans-serif; margin-top: 80px; padding: 20px;">
  <% @livros.each do |livro| %>
    <%= render livro %>
  <% end %>
  <% if notice %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

</div>

app/app/views/livros/new.html.erb
<h2 class="text-center font-roboto-mono padding-cadastrar">
  Cadastro de Livros
</h2>

<%= render "form", livro: @livro %>

<div class="position-absolute top-0 start-0 mt-3 ms-3 font-roboto-mono">
  <%= link_to livros_path, class: 'd-flex align-items-center link' do %>
    <i class="bi bi-arrow-return-left fs-3"></i>
    <span class="ms-2 fs-6">Voltar livro</span> 
  <% end %>
</div>

app/app/views/livros/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="position-absolute top-0 start-0 mt-3 ms-3 font-roboto-mono">
  <%= link_to livros_path, class: 'd-flex align-items-center link' do %>
    <i class="bi bi-arrow-return-left fs-3"></i>
    <span class="ms-2 fs-6">Voltar livro</span> 
  <% end %>
</div>

<div class="container">
  <div class="content">
    <%= render @livro %>

    <div class="button-container mt-3">
      <%= link_to "Editar o livro", edit_livro_path(@livro), class: 'btn btn-primary me-2' %>
      <%= button_to "Excluir Livro", @livro, method: :delete, class: 'btn btn-danger' %>
    </div>
  </div>
</div>

<style>
html, body {
  height: 100%;
  margin: 0;
}

.container {
  display: flex;
  justify-content: center; 
  align-items: center;
  height: 100vh; 
}

.content {
  display: flex;
  flex-direction: column;
  align-items: flex-end; 
  width: 100%; 
}

.button-container {
  display: flex;
  gap: 1rem; 
  margin-top: 1rem; 
}

.position-absolute {
  z-index: 1000; 
}
</style>