app/config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  get 'users/create'
  # Defina a rota root 
  root 'livros#index'

   # Rotas de autenticação
   get 'login', to: 'sessions#new'
   post 'login', to: 'sessions#create'
   delete 'logout', to: 'sessions#destroy'
 
   # Rotas para usuários
   get 'signup', to: 'users#new'
   post 'signup', to: 'users#create'
   
  # Recursos para os controladores
  resources :funcionarios
  resources :usuarios
  resources :livros
  resources :emprestimos

  # Rota para verificar a saúde do Rails
  get "up" => "rails/health#show", as: :rails_health_check
end

app/app/models/emprestimo.rb
class Emprestimo < ApplicationRecord
    belongs_to :usuario
    belongs_to :livro
  
    validates :data_emprestimo, presence: true
    validates :data_devolucao, presence: true
    validates :usuario_id, presence: true
    validates :livro_id, presence: true
  end
  

app/app/controllers/emprestimos_controller.rb
class EmprestimosController < ApplicationController
    before_action :set_emprestimo, only: %i[show edit update destroy]
  
    def index
      @emprestimos = Emprestimo.all
    end
  
    def show
    end
  
    def new
      @emprestimo = Emprestimo.new
    end
  
    def edit
    end
  
    def create
      @emprestimo = Emprestimo.new(emprestimo_params)
  
      respond_to do |format|
        if @emprestimo.save
          format.html { redirect_to @emprestimo}
          format.json { render :show, status: :created, location: @emprestimo }
        else
          format.html { render :new }
          format.json { render json: @emprestimo.errors, status: :unprocessable_entity }
        end
      end
    end
  
    def update
      respond_to do |format|
        if @emprestimo.update(emprestimo_params)
          format.html { redirect_to @emprestimo }
          format.json { render :show, status: :ok, location: @emprestimo }
        else
          format.html { render :edit }
          format.json { render json: @emprestimo.errors, status: :unprocessable_entity }
        end
      end
    end
  

    def destroy
      @emprestimo.destroy
      respond_to do |format|
        format.html { redirect_to emprestimos_url }
        format.json { head :no_content }
      end
    end
  
    private
      
      def set_emprestimo
        @emprestimo = Emprestimo.find(params[:id])
      end
  
      def emprestimo_params
        params.require(:emprestimo).permit(:usuario_id, :livro_id, :data_emprestimo, :data_devolucao)
      end
  end

app/app/views/emprestimos/_form.html.erb
<%= form_for(@emprestimo, html: { multipart: true }) do |f| %>
  <% if @emprestimo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@emprestimo.errors.count, "erro") %> impediram que este empréstimo fosse salvo:</h2>
  
      <ul>
        <% @emprestimo.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <%= f.label :usuario_id, 'Usuário', class: "font-roboto-mono" %>
    <%= f.select :usuario_id, Usuario.all.collect { |u| [u.nome, u.id] }, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.label :livro_id, 'Livro', class: "font-roboto-mono" %>
    <%= f.select :livro_id, Livro.all.collect { |l| [l.nome, l.id] }, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.label :data_emprestimo, 'Data Empréstimo', class: "font-roboto-mono" %>
    <%= f.date_field :data_emprestimo, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.label :data_devolucao, 'Data Devolução', class: "font-roboto-mono" %>
    <%= f.date_field :data_devolucao, class: "form-control" %>
  </div>

  <%= f.submit "Salvar", class: "btn btn-primary btn-padded" %>
<% end %>

app/app/views/emprestimos/edit.html.erb
<h1 class="text-center font-roboto-mono">Editar Empréstimo</h1>


<div class="position-absolute top-0 start-0 mt-3 ms-3 font-roboto-mono">
  <%= link_to emprestimo_path, class: 'd-flex align-items-center link' do %>
    <i class="bi bi-arrow-return-left fs-3"></i>
    <span class="ms-2 fs-6">Voltar emprestimo</span> 
  <% end %>
</div>

<div class="container d-flex justify-content-center align-items-center min-vh-100">
  <div class="content w-100" style="max-width: 1600px;">
    <%= render "form", emprestimo: @emprestimo %>
  </div>
</div>

app/app/views/emprestimos/index.html.erb
<div class="padding-cadastrar">
  <h1 class="font-roboto-mono text-center">Empréstimos</h1>

  <% if @emprestimos.present? %>
    <table class="table table-bordered font-roboto-mono w-75 mx-auto mt-4">
      <thead>
        <tr>
          <th>Usuário</th>
          <th>Livro</th>
          <th>Data Empréstimo</th>
          <th>Data Devolução</th>
          <th colspan="2">Ações</th>
        </tr>
      </thead>
      <tbody>
        <% @emprestimos.each do |emprestimo| %>
          <tr id="<%= dom_id emprestimo %>">
            <td><%= emprestimo.usuario.nome %></td>
            <td><%= emprestimo.livro.nome %></td>
            <td><%= emprestimo.data_emprestimo %></td>
            <td><%= emprestimo.data_devolucao %></td>
            <td class="text-center">
              <%= link_to edit_emprestimo_path(emprestimo), class: "btn btn-sm" do %>
                <i class="bi bi-pencil"></i>
              <% end %>
            </td>
            <td class="text-center">
              <%= link_to emprestimo_path(emprestimo), method: :delete, data: { confirm: "Você tem certeza?" }, class: "btn btn-sm" do %>
                <i class="bi bi-trash"></i>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p class="text-center font-roboto-mono">Nenhum empréstimo encontrado.</p>
  <% end %>

  <div class="d-flex justify-content-end mt-3" style="padding: 40px;">
  <%= link_to 'Novo Empréstimo', new_emprestimo_path, class: "btn btn-success font-roboto-mono btn-move-left" %>
</div>

</div>

app/app/views/emprestimos/new.html.erb
<h2 class="text-center font-roboto-mono padding-cadastrar">
    Novo emprestimo
</h2>

<%= render 'form', emprestimo: @emprestimo %>

<div class="position-absolute top-0 start-0 mt-3 ms-3 font-roboto-mono">
  <%= link_to emprestimos_path, class: 'd-flex align-items-center link' do %>
    <i class="bi bi-arrow-return-left fs-3"></i>
    <span class="ms-2 fs-6">Voltar Emprestimo</span> 
  <% end %>
</div>

app/app/views/emprestimos/show.html.erb
<h1>Empréstimo</h1>

<p>
  <b>Usuário:</b>
  <%= @emprestimo.usuario.nome %>
</p>

<p>
  <b>Livro:</b>
  <%= @emprestimo.livro.nome %>
</p>

<p>
  <b>Data Empréstimo:</b>
  <%= @emprestimo.data_emprestimo %>
</p>

<p>
  <b>Data Devolução:</b>
  <%= @emprestimo.data_devolucao %>
</p>

<div class="container">
  <div class="content">
    <div class="button-container mt-3">
      <%= link_to 'Editar', edit_emprestimo_path(@emprestimo), class: 'btn btn-primary me-2' %>
      <%= link_to 'Voltar', emprestimos_path, class: 'btn btn-secondary' %>
    </div>
  </div>
</div>

<style>
html, body {
  height: 100%;
  margin: 0;
}

.container {
  display: flex;
  justify-content: center; 
  align-items: center;
  height: 100vh; 
}

.content {
  display: flex;
  flex-direction: column;
  align-items: flex-end; 
  width: 100%; 
}

.button-container {
  display: flex;
  gap: 1rem; 
  margin-top: 1rem; 
}
</style>