app/config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  get 'users/create'
  # Defina a rota root 
  root 'livros#index'

   # Rotas de autenticação
   get 'login', to: 'sessions#new'
   post 'login', to: 'sessions#create'
   delete 'logout', to: 'sessions#destroy'
 
   # Rotas para usuários
   get 'signup', to: 'users#new'
   post 'signup', to: 'users#create'
   
  # Recursos para os controladores
  resources :funcionarios
  resources :usuarios
  resources :livros
  resources :emprestimos

  # Rota para verificar a saúde do Rails
  get "up" => "rails/health#show", as: :rails_health_check
end

app/app/models/usuario.rb
class Usuario < ApplicationRecord

    validates :email, presence: { message: 'não pode ficar em branco' }
    validates :nome, presence: { message: 'não pode ficar em branco' }
    validates :cpf, presence: { message: 'não pode ficar em branco' }
    validates :telefone, presence: { message: 'não pode ficar em branco' }
    
end

app/app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: %i[ show edit update destroy ]

 
  def index
    @usuarios = Usuario.all
  end


  def show
  end

  
  def new
    @usuario = Usuario.new
  end

  def edit
  end

  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to usuario_url(@usuario), notice: "Usuario was successfully created." }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to usuario_url(@usuario), notice: "Usuario was successfully updated." }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @usuario.destroy!

    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: "Usuario was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    def usuario_params
      params.require(:usuario).permit(:email, :nome, :cpf, :telefone)
    end
end

app/app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/app/views/usuarios/_form.html.erb
<%= form_with(model: usuario) do |form| %>
  <% if usuario.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
        <% usuario.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :cpf, style: "display: block" %>
    <%= form.text_field :cpf %>
  </div>

  <div>
    <%= form.label :telefone, style: "display: block" %>
    <%= form.text_field :telefone %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/app/views/usuarios/_usuario.html.erb
<div id="<%= dom_id usuario %>">
  <p>
    <strong>Email:</strong>
    <%= usuario.email %>
  </p>

  <p>
    <strong>Nome:</strong>
    <%= usuario.nome %>
  </p>

  <p>
    <strong>Cpf:</strong>
    <%= usuario.cpf %>
  </p>

  <p>
    <strong>Telefone:</strong>
    <%= usuario.telefone %>
  </p>

</div>

app/app/views/usuarios/edit.html.erb
<h1>Editing usuario</h1>

<%= render "form", usuario: @usuario %>

<br>

<div>
  <%= link_to "Show this usuario", @usuario %> |
  <%= link_to "Back to usuarios", usuarios_path %>
</div>

app/app/views/usuarios/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Usuarios</h1>

<div id="usuarios">
  <% @usuarios.each do |usuario| %>
    <%= render usuario %>
    <p>
      <%= link_to "Show this usuario", usuario %>
    </p>
  <% end %>
</div>

<%= link_to "New usuario", new_usuario_path %>

app/app/views/usuarios/new.html.erb
<h1>New usuario</h1>

<%= render "form", usuario: @usuario %>

<br>

<div>
  <%= link_to "Back to usuarios", usuarios_path %>
</div>

app/app/views/usuarios/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @usuario %>

<div>
  <%= link_to "Edit this usuario", edit_usuario_path(@usuario) %> |
  <%= link_to "Back to usuarios", usuarios_path %>

  <%= button_to "Destroy this usuario", @usuario, method: :delete %>
</div>